services:

  sanitizer:
    build: ./sanitizer
    container_name: sanitizer_service
    ports:
      - "8000:8000"
    networks:
      - llm_net
    volumes:
      - ./sanitizer:/app

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator_service
    depends_on:
      - sanitizer
    ports:
      - "7000:7000"
    networks:
      - llm_net
    volumes:
      - ./orchestrator:/app

  guardrail:
    build: ./guardrail
    container_name: guardrail_service
    ports:
      - "6000:6000"
    networks:
      - llm_net
    volumes:
      - ./guardrail:/app

  bias_guardrail:
    build: ./bias_guardrail
    container_name: bias_guardail_service
    ports:
      - "5000:5000"
    networks:
      - llm_net
    volumes:
      - ./bias_guardrail:/app

  output_guardrail:
    build: ./output_guardrail
    container_name: output_guardrail_service
    ports:
      - "4000:4000"
    networks:
      - llm_net
    volumes:
      - ./output_guardrail:/app

  streamlit:
    build: ./streamlit_app
    container_name: streamlit_service
    depends_on:
      - orchestrator
    ports:
      - "8501:8501"
    networks:
      - llm_net
    volumes:
      - ./streamlit_app:/app

networks:
  llm_net:
    driver: bridge